spring.application.name=RealEstate

spring.datasource.url=jdbc:mysql://localhost:3306/RealEstate
spring.datasource.username=root
spring.datasource.password=narayan8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server port (optional, default is 8080)
#server.port=9098

# JSP View Resolver configuration
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

# Set web application type to servlet for WAR deployment
spring.main.web-application-type=servlet